package com.oztechan.ccc.common.core.network.error

internal class TerminationException(cause: Throwable) : Throwable(cause)
