package com.oztechan.ccc.common.core.network.error

internal class UnknownNetworkException(cause: Throwable) : Throwable(cause)
